brd = {
    'name': ('Raspberry Pi B+/2'),
    'port': {
        'rpigpio': {
            'gpio' : {
                # BCM/Functional RPi pin names.
                'bcm2_sda'   : '3',
                'bcm3_scl'   : '5',
                'bcm4_gpclk0': '7',
                'bcm17'      : '11',
                'bcm27_pcm_d': '13',
                'bcm22'      : '15',
                'bcm10_mosi' : '19',
                'bcm9_miso'  : '21',
                'bcm11_sclk' : '23',
                'bcm5'       : '29',
                'bcm6'       : '31',
                'bcm13'      : '33',
                'bcm19_miso' : '35',
                'bcm26'      : '37',
                'bcm21_sclk' : '40',
                'bcm20_mosi' : '38',
                'bcm16'      : '36',
                'bcm12'      : '32',
                'bcm7_ce1'   : '26',
                'bcm8_ce0'   : '24',
                'bcm25'      : '22',
                'bcm24'      : '18',
                'bcm23'      : '16',
                'bcm18_pcm_c': '12',
                'bcm15_rxd'  : '10',
                'bcm14_txd'  : '8',

                # Functional RPi pin names.
                # 'bcm2' : '3',
                # 'bcm3' : '5',
                # 'bcm4' : '7',
                # 'bcm5' : '29',
                # 'bcm6' : '31',
                # 'bcm7' : '26',
                # 'bcm8' : '24',
                # 'bcm9' : '21',
                # 'bcm10': '19',
                # 'bcm11': '23',
                # 'bcm12': '32',
                # 'bcm13': '33',
                # 'bcm14': '8',
                # 'bcm15': '10',
                # 'bcm16': '36',
                # 'bcm17': '11',
                # 'bcm18': '12',
                # 'bcm19': '35',
                # 'bcm20': '38',
                # 'bcm21': '40',
                # 'bcm22': '15',
                # 'bcm23': '16',
                # 'bcm24': '18',
                # 'bcm25': '22',
                # 'bcm26': '37',
                # 'bcm27': '13',

                # Positional RPi pin names.
                # 'gpio03': '3',
                # 'gpio05': '5',
                # 'gpio07': '7',
                # 'gpio29': '29',
                # 'gpio31': '31',
                # 'gpio26': '26',
                # 'gpio24': '24',
                # 'gpio21': '21',
                # 'gpio19': '19',
                # 'gpio23': '23',
                # 'gpio32': '32',
                # 'gpio33': '33',
                # 'gpio08': '8',
                # 'gpio10': '10',
                # 'gpio36': '36',
                # 'gpio11': '11',
                # 'gpio12': '12',
                # 'gpio35': '35',
                # 'gpio38': '38',
                # 'gpio40': '40',
                # 'gpio15': '15',
                # 'gpio16': '16',
                # 'gpio18': '18',
                # 'gpio22': '22',
                # 'gpio37': '37',
                # 'gpio13': '13',
            }
        }
    }
}
